### ISSUE TITLE
Error running npx directly

### ISSUE THREAD

**Issue by grantkellyADSK** [patheard/test-cuke#3]
Hello,

I get an error when attempting to run the tests with `npx` directly (the same command that is in `package.json`). I do not understand why there would be differences between invoking with `npm` vs. `npx`.

This works fine:

```
➜  test-cuke git:(master) npm test

> test-cuke@1.0.0 test /private/tmp/test-cuke
> npx cucumber-js --require ./**/cucumber-puppeteer/**/features/**/*.js --require ./features/**/*.js

Before everything
.Before "Check title"
...After "Check title"
..All done!


1 scenario (1 passed)
2 steps (2 passed)
0m06.361s
```

Here is the error:

```
➜  test-cuke git:(master) npx cucumber-js --require ./**/cucumber-puppeteer/**/features/**/*.js --require ./features/**/*.js
Error: Undefined parameter type {string-env}
    at UndefinedParameterTypeError.CucumberExpressionError [as constructor] (/private/tmp/test-cuke/node_modules/cucumber-expressions/dist/src/Errors.js:19:42)
    at new UndefinedParameterTypeError (/private/tmp/test-cuke/node_modules/cucumber-expressions/dist/src/Errors.js:47:23)
    at /private/tmp/test-cuke/node_modules/cucumber-expressions/dist/src/CucumberExpression.js:101:23
    at String.replace (<anonymous>)
    at CucumberExpression.processParameters (/private/tmp/test-cuke/node_modules/cucumber-expressions/dist/src/CucumberExpression.js:93:27)
    at new CucumberExpression (/private/tmp/test-cuke/node_modules/cucumber-expressions/dist/src/CucumberExpression.js:46:21)
    at buildStepDefinitionFromConfig (/private/tmp/test-cuke/node_modules/cucumber/lib/support_code_library_builder/build_helpers.js:158:22)
    at options.stepDefinitions.options.stepDefinitionConfigs.map.config (/private/tmp/test-cuke/node_modules/cucumber/lib/support_code_library_builder/index.js:83:134)
    at Array.map (<anonymous>)
    at SupportCodeLibraryBuilder.finalize (/private/tmp/test-cuke/node_modules/cucumber/lib/support_code_library_builder/index.js:83:71)
    at Cli.getSupportCodeLibrary (/private/tmp/test-cuke/node_modules/cucumber/lib/cli/index.js:120:50)
    at Cli.run (/private/tmp/test-cuke/node_modules/cucumber/lib/cli/index.js:141:37)
➜  test-cuke git:(master)
```

**Comment by grantkellyADSK** [comment]
I believe this to be a shell globbing issue. The following works (at least in zsh)

`npx cucumber-js --require "./**/cucumber-puppeteer/**/features/**/*.js" --require "./features/**/*.js"`
